name: buzzgo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.10.7
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Location & Maps
  geolocator: ^10.1.1
  geocoding: ^2.2.2
  google_maps_flutter: ^2.10.1
  
  # Storage & Caching
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  cached_network_image: ^3.4.1
  
  # Network & HTTP
  dio: ^5.9.0
  http: ^1.5.0
  connectivity_plus: ^6.1.0
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Logging
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true