name: buzzgo
description: "BuzzGo - Local Event Finder App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core Dependencies
  provider: ^6.1.2
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  
  # HTTP & Networking
  http: ^1.1.2
  dio: ^5.3.2
  connectivity_plus: ^6.1.5
  
  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.5.0
  location: ^8.0.1
  
  # Authentication
  google_sign_in: ^6.1.6
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  image_cropper: ^9.1.0
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Date & Time
  intl: ^0.20.2
  
  # URL Launcher
  url_launcher: ^6.2.1
  
  # Payments
  crypto: ^3.0.3
  
  # Utilities
  uuid: ^4.1.0
  path_provider: ^2.1.1
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0
  
  # Animations
  lottie: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # File Handling
  file_picker: ^10.3.2
  path: ^1.8.3
  
  # Notifications
  flutter_local_notifications: ^19.4.1
  
  # Biometrics
  local_auth: ^2.1.6
  
  # Social Sharing
  share_plus: ^11.1.0
  
  # WebView
  webview_flutter: ^4.4.2
  
  # Charts (for analytics)
  fl_chart: ^1.0.0
  
  # Carousel
  carousel_slider: ^5.1.1
  
  # Pull to Refresh
  pull_to_refresh: ^2.0.0
  
  # Shimmer Loading
  shimmer: ^3.0.0
  
  # Rating
  flutter_rating_bar: ^4.0.1
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Video Player
  video_player: ^2.8.1
  
  # Audio Player
  audioplayers: ^6.5.0
  
  # JSON Annotation
  json_annotation: ^4.8.1
  
  # Equatable
  equatable: ^2.0.5
  
  # Logging
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Remove assets section for now (add back when you create the folders)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  #   - assets/fonts/

  # Remove fonts section for now (add back when you have font files)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700