name: buzzgo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5
  
  # Firebase - using latest compatible versions
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.10.7
  firebase_core_web: ^2.24.0
  firebase_app_check: ^0.2.1+7


  # Utilities
  intl: ^0.17.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Logging
  logger: ^2.4.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  
  # Location Services
  geolocator: ^10.1.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1
  
  # Storage & Caching
  shared_preferences: ^2.2.3
  
  # Network & Connectivity
  connectivity_plus: ^6.0.2
  http: ^1.2.1
  
  # Payment Integration
  mpesa_flutter_plugin: ^1.3.0
  
  # External APIs
  dio: ^5.4.3
  
  # Google Sign-In
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
