name: buzzgo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # JavaScript interop for Firebase web
  js: ^0.6.7
  
  # State Management
  provider: ^6.1.1
  
  # Firebase - using compatible versions
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.7
  firebase_analytics: ^10.4.5
  
  # Utilities
  intl: ^0.18.1
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true