// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCxtAmolcmgksYvFtr937KbWHbNMw_p_M',
    appId: '1:572107014835:web:d412d9c9fd4f43f5d526c6',
    messagingSenderId: '572107014835',
    projectId: 'kupatanakenya',
    authDomain: 'kupatanakenya.firebaseapp.com',
    storageBucket: 'kupatanakenya.firebasestorage.app',
    measurementId: 'G-GSMXWVHMXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtEFlN3DecrHx2yuib3WsbZ0EkVMr4dw',
    appId: '1:572107014835:android:b961abbfcd9df224d526c6',
    messagingSenderId: '572107014835',
    projectId: 'kupatanakenya',
    storageBucket: 'kupatanakenya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAr3pZFIw_ojzdGWHeoB9Mex9XH0yiSQ',
    appId: '1:572107014835:ios:8069d083f23ed219d526c6',
    messagingSenderId: '572107014835',
    projectId: 'kupatanakenya',
    storageBucket: 'kupatanakenya.firebasestorage.app',
    iosBundleId: 'com.example.buzzgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdAr3pZFIw_ojzdGWHeoB9Mex9XH0yiSQ',
    appId: '1:572107014835:ios:8069d083f23ed219d526c6',
    messagingSenderId: '572107014835',
    projectId: 'kupatanakenya',
    storageBucket: 'kupatanakenya.firebasestorage.app',
    iosBundleId: 'com.example.buzzgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCxtAmolcmgksYvFtr937KbWHbNMw_p_M',
    appId: '1:572107014835:web:4b79f03bb52e8247d526c6',
    messagingSenderId: '572107014835',
    projectId: 'kupatanakenya',
    authDomain: 'kupatanakenya.firebaseapp.com',
    storageBucket: 'kupatanakenya.firebasestorage.app',
    measurementId: 'G-YT8NNX0ZVS',
  );

}